version: '3.1'
networks:
  main:
services:
  redboxportal:
    build: .
    image: qcifengineering/redbox-portal:latest
    ports:
      - "1500:1500"
    user: node
    volumes:
      - ".:/opt/redbox-portal:delegated"
      - "./dev/attachments:/attachments:delegated"
      - "./dev/publication:/publication:delegated"
      - "./dev/hooks:/opt/hooks:delegated"
    expose:
      - "1500"
    environment:
      - NODE_ENV=docker
      - PORT=1500
      - sails_redbox__apiKey=c8e844fc-8550-497f-b970-7900ec8741ca
      - sails_record__baseUrl__redbox=http://redbox:9000/redbox
      # When testing using the API
      # - sails_auth__default__local__default__token=d077835a-696b-4728-85cf-3ffd57152b1e
      # - sails_security__csrf=false
    networks:
      main:
        aliases:
          - rbportal
    entrypoint: /bin/bash -c "cd /opt/redbox-portal && node app.js"
  mongodb:
    image: mvertes/alpine-mongo:latest
    volumes:
      - "./devdata:/devdata:delegated"
      - "./dev/mongo/data/db:/data/db:delegated"
      - "./dev/log/mongo:/var/log/mongo:delegated"
    networks:
      main:
        aliases:
          - mongodb
    ports:
      - "27017:27017"
  solr:
    image: solr:8.6.3
    expose:
      - "8983"
    ports:
      - "8983:8983"
    networks:
      main:
        aliases:
          - solr
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - redbox
